### ISSUE TITLE
Cannot auto generate between double quotes

### ISSUE THREAD

**Issue by jeffsuto** [austenc/vscode-blade-spacer#12] opened 2020-01-29 22:30 UTC
I have a problem with my blade spacer extension:

When i press the left curly bracket twice between double quotes character or other character, blade spacer cannot generate the echo curly brackets:
![image](https://user-images.githubusercontent.com/39300886/73402867-cae15180-4320-11ea-8176-215b356bd95d.png)

My expectation is like this:
![image](https://user-images.githubusercontent.com/39300886/73403046-32979c80-4321-11ea-810b-9f215661298c.png)

**Comment by austenc** [comment] 2020-01-30 00:29
Hi @jeffsuto 

This is a duplicate of https://github.com/austenc/vscode-blade-spacer/issues/6. Please let me know if this solution doesn't work for you!

**Closed as completed by austenc** 2020-01-30 00:29 UTC

**Comment by jeffsuto** [comment] 2020-01-30 00:46
thanks, it works.
